services:
  - type: web
    name: todo-backend
    env: docker
    plan: free
    dockerfilePath: Dockerfile.backend
    autoDeploy: true
    envVars:
      - key: REDIS_URL
        fromService:
          name: todo-redis
          type: redis
      - key: PGUSER
        value: your_pg_user
      - key: PGHOST
        value: your_pg_host
      - key: PGPASSWORD
        value: your_pg_password
      - key: PGDATABASE
        value: your_pg_database
      - key: PGPORT
        value: "5432"

  - type: web
    name: todo-frontend
    env: docker
    plan: free
    dockerfilePath: Dockerfile.frontend
    autoDeploy: true

  - type: redis
    name: todo-redis
    plan: free
