services:
  - type: web
    name: todo-backend
    env: docker
    plan: free
    dockerfilePath: Dockerfile.backend
    autoDeploy: true

  - type: web
    name: todo-frontend
    env: docker
    plan: free
    dockerfilePath: Dockerfile.frontend
    autoDeploy: true
