services:
  - type: web
    name: todo-backend
    env: docker
    plan: free
    dockerfilePath: Dockerfile.backend
    autoDeploy: true
    envVars:
      - key: REDIS_URL
        fromService:
          name: todo-redis
          type: redis
          property: connectionString

  - type: web
    name: todo-frontend
    env: docker
    plan: free
    dockerfilePath: Dockerfile.frontend
    autoDeploy: true

  - type: redis
    name: todo-redis
    plan: free
